- screens/popups/import/import.gui_script
The point of this is me learning how to set up the project and use GIT pull requests.
To that end, I felt like doing a simple change to improve the text in the Import dialog. I do not understand how Defold's GUI system works - the anchoring and pivoting I tried to use was giving me fishy results.
> Updating import GUI

- screens/change_pokemon/add/add.gui_script
- screens/change_pokemon/import/import.gui_script
- screens/popups/import/import.gui_script
> Fixed incorrect add Pokémon notification

- pokedex/trainer.lua
- screens/popups/import/import.gui_script
- screens/trainer/trainer.gui_script
> Fixed Pokémon attack type bonuses not working

- pokedex/pokemon.lua
- screens/popups/transfer_pokemon/transfer.gui_script
> Fixing profile corruption related to Struggle move

- pokedex/moves.lua
- pokedex/pokemon.lua
- screens/change_pokemon/change_pokemon.lua
- screens/party/components/moves.lua
- screens/popups/move_info/move_info.gui_script
- It no longer shows -/+ buttons (which are buggy anyway, see #407
- it no longer says Unlimited/99 on the move details screen
- It no longer is available to choose when choosing a move for a Pokemon (though if the Pokemon already knows it, it will be available to swap out)
- It shows up on every Pokemon's move list on the party screen (at the bottom)
Also, no move (including Struggle) will show the "Reset" button on the move details if it's already at max PP.
#408
> A variety of bugfixes and usability improvements related to Struggle

- screens/party/components/meters.lua
- utils/gui_colors.lua
Change colors depending on your current HP, I put all the colors in the `gui_colors` module to make it easier to tweak them all at the same time.
Fixes: #440
> Change colors depending on your current HP

- screens/popups/transfer_pokemon/transfer.gui_script
> Fixed move button being visible when you only have one Party Pokemon

- assets/datafiles/pokemon/Bunnelby.json
- assets/datafiles/pokemon/Diggersby.json
- assets/datafiles/pokemon/Diglett.json
- assets/datafiles/pokemon/Drilbur.json
- assets/datafiles/pokemon/Dugtrio.json
- assets/datafiles/pokemon/Dunsparce.json
- assets/datafiles/pokemon/Durant.json
- assets/datafiles/pokemon/Excadrill.json
- assets/datafiles/pokemon/Onix.json
- assets/datafiles/pokemon/Sandshrew.json
- assets/datafiles/pokemon/Sandslash.json
- assets/datafiles/pokemon/Steelix.json
- pokedex/pokedex.lua
- pokedex/pokemon.lua
- screens/party/party.gui
- templates/party_pokemon.gui
- templates/pokemon_info.gui
- tools/scripts/source_data/converters/pokemon.py
> Adding Burrowing speed

- screens/popups/fakemon/fakemon.gui_script
> Fixed bug where Fakemon search didn't work

- pokedex/profiles.lua
- screens/trainer/trainer.gui
- screens/trainer/trainer.gui_script
> Can now change active profile name

- screens/storage/storage.gui_script
> Storing the action position in self.

- assets/datafiles/abilities.json
- assets/datafiles/items.json
- assets/datafiles/moves/Bullet Punch.json
- assets/datafiles/moves/Hail.json
- assets/datafiles/moves/Hydro Pump.json
- assets/datafiles/moves/Sandstorm.json
- assets/datafiles/moves/Struggle.json
- assets/datafiles/pokemon/Empoleon.json
- assets/datafiles/pokemon/Meowstic-f.json
- assets/datafiles/pokemon/Meowstic-m.json
- assets/datafiles/pokemon/Piplup.json
- assets/datafiles/pokemon/Prinplup.json
- screens/popups/status_effects/status_effects.gui
- tools/scripts/source_data/assets/extra/abilities.json
- tools/scripts/source_data/converters/other.py
- tools/scripts/source_data/util/util.py
Fixes #472 
As well as some other data that I have not generated after fixing it
> Data update 7/8/2020

- screens/change_pokemon/import/import.gui_script
> Importing Fakemon didn't work because it couldn't set the image

- pokedex/storage.lua
> Fix for temp_hp nil

- screens/trainer/trainer.gui_script
> Fixing crashes associated with changing profile name

- pokedex/pokemon.lua
- pokedex/trainer.lua
- screens/trainer/trainer.gui
- screens/trainer/trainer.gui_script
> Option to apply stab to all moves

- pokedex/pokemon.lua
- pokedex/trainer.lua
- screens/trainer/trainer.gui
- screens/trainer/trainer.gui_script
fixes #400
Adding two additional buttons to the trainer section. These ones add bonus damage depending on the Pokemon type or the move type.
Because of the changes in #503 I didn't have to add a ton of gui stuff, pretty neat.
> Damage bonus depending on Pokemon and/or Move type

- pokedex/pokemon.lua
> Fixed incorrect logic around determining move power

- pokedex/pokedex.lua
Fix to enable genderless pokemon to evolve
> #578 genderless pokemon evolve

- screens/party/components/status_effects.lua
- screens/party/party.gui
- templates/party_pokemon.gui
> #553 reduce status effect buttons hitbox

- screens/network/connect.gui
- screens/network/connect.gui_script
> Adding help text to Connect screen

- pokedex/pokedex.lua
- pokedex/pokemon.lua
- screens/change_pokemon/add/add.gui
- screens/change_pokemon/change_pokemon.gui
- screens/change_pokemon/change_pokemon.lua
- screens/change_pokemon/edit/edit.gui
- screens/change_pokemon/import/import.gui
- screens/party/components/information.lua
- screens/party/party.gui
- templates/party_pokemon.gui
- templates/pokemon_info.gui
- utils/messages.lua
(Merging into generation_vii branch)
This adds a field into the edit section where you can add more skills
Closes #633
> adding skills

- pokedex/pokedex.lua
- pokedex/pokemon.lua
- screens/change_pokemon/change_pokemon.lua
- screens/change_pokemon/edit/edit.gui_script
- screens/generate_pokemon/generate_pokemon.lua
The new hit dice will now apply, assuming you were letting the app calculate the pokemon's HP.
Also fixing a bug with the max HP reset to default - it was calling a function that did not exist.
Fixes #629
> Upgrading pokemon (like Muk) that had hit dice changes

- pokedex/share.lua
> Share pokemon trailing }

- pokedex/share.lua
- screens/popups/import/import.gui_script
- screens/popups/qr_read/qr_read.gui_script
Don't think we need to do it for the network as it checks version but figured there was no harm?
> upgrade a pokemon you recieve

- pokedex/pokemon.lua
In some fringe cases the app can not find which Pokemon your current Pokemon evolved from, this is important when trying to reset the HP. If we can not find which we are now giving it MissingNo as a fallback.
fixes #670
> App stalling on start

- pokedex/pokedex.lua
> Fixed Porygon evolution issue with strict genders on

- pokedex/pokemon.lua
> Fixing skill removal bug

- utils/utils.lua
> Fix for Arceus not being addable.

- screens/generate_pokemon/generate_pokemon.gui_script
- screens/generate_pokemon/random_pokemon/random_pokemon.gui_script
- utils/utils.lua
> UNTESTED changes to a few rnd.range calls
